name: Sync schema.json to LSP repo

on:
  push:
    branches: [main]
    paths:
      - "src/makim/schema.json"

jobs:
  sync-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Makim repo
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Clone LSP repo
        run: |
          git clone https://github.com/makim-org/makim-lsp.git
          cd makim-lsp
          git checkout -b sync-schema-$(date +%s)

          cp ./src/makim/schema.json ./packages/language-server/src/schema/makim.schema.json

          git add .
          git commit -m "chore(schema): sync from Makim"

          git push origin HEAD

      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: "chore(schema): sync from Makim"
          branch: sync-schema-${{ github.run_id }}
          title: "Sync schema.json from Makim"
          body: |
            This PR was automatically generated by a GitHub Action to sync `schema.json` from the Makim repo.
          base: main
